<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net9.0-windows</TargetFramework><UseWPF>true</UseWPF><ApplicationIcon>Assets/App.ico</ApplicationIcon><AssemblyName>GameFromHome</AssemblyName><Version>0.2.2</Version><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup><ItemGroup><ProjectReference Include="../GameFromHome.Core/GameFromHome.Core.csproj"/><Resource Include="Assets/App.png"/></ItemGroup></Project>
